In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\Ujjwal\Desktop\Heart.csv")

In [3]:
data.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [4]:
data.tail()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [5]:
data.shape

(303, 15)

In [6]:
data.describe()

,Unnamed: 0,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000
mean,152.000000,54.438944,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241
std,87.612784,9.038662,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438
min,1.000000,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,76.500000,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,152.000000,56.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,227.500000,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,303.000000,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000

In [7]:
data.columns

Index(['Unnamed: 0', 'Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='object')

In [8]:
data.rename(columns={'Sex':'Gender'}, inplace=True)
data['Gender']

0      1
1      1
2      1
3      1
4      0
      ..
298    1
299    1
300    1
301    0
302    1
Name: Gender, Length: 303, dtype: int64

In [9]:
data.isnull().sum()

Unnamed: 0    0
Age           0
Gender        0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [10]:
data.dtypes

Unnamed: 0      int64
Age             int64
Gender          int64
ChestPain      object
RestBP          int64
Chol            int64
Fbs             int64
RestECG         int64
MaxHR           int64
ExAng           int64
Oldpeak       float64
Slope           int64
Ca            float64
Thal           object
AHD            object
dtype: object

In [11]:
data['Age'].mean()

54.43894389438944

In [12]:
data['Age'].min()

29

In [13]:
data['Age'].max()

77

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
train,test = train_test_split(data, random_state=0, test_size=0.3)

In [16]:
train.shape

(212, 15)

In [17]:
test.shape

(91, 15)

In [18]:
train

,Unnamed: 0,Age,Gender,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
137,138,62,1,nontypical,120,281,0,2,103,0,1.4,2,1.0,reversable,Yes
106,107,59,1,asymptomatic,140,177,0,0,162,1,0.0,1,1.0,reversable,Yes
284,285,61,1,asymptomatic,148,203,0,0,161,0,0.0,1,1.0,reversable,Yes
44,45,61,0,asymptomatic,130,330,0,2,169,0,0.0,1,0.0,normal,Yes
139,140,51,1,nonanginal,125,245,1,2,166,0,2.4,2,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,252,58,1,asymptomatic,146,218,0,0,105,0,2.0,2,1.0,reversable,Yes
192,193,43,1,asymptomatic,132,247,1,2,143,1,0.1,2,NaN,reversable,Yes
117,118,35,0,asymptomatic,138,183,0,0,182,0,1.4,1,0.0,normal,No
47,48,50,1,asymptomatic,150,243,0,2,128,0,2.6,2,0.0,reversable,Yes
172,173,59,0,asymptomatic,174,249,0,0,143,1,0.0,2,0.0,normal,Yes

In [19]:
test

,Unnamed: 0,Age,Gender,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
225,226,34,0,nontypical,118,210,0,0,192,0,0.7,1,0.0,normal,No
152,153,67,0,nonanginal,115,564,0,2,160,0,1.6,2,0.0,reversable,No
228,229,54,1,asymptomatic,110,206,0,2,108,1,0.0,2,1.0,normal,Yes
201,202,64,0,asymptomatic,180,325,0,0,154,1,0.0,1,0.0,normal,No
52,53,44,1,asymptomatic,112,290,0,2,153,0,0.0,1,1.0,normal,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,254,51,0,nonanginal,120,295,0,2,157,0,0.6,1,0.0,normal,No
293,294,63,1,asymptomatic,140,187,0,2,144,1,4.0,1,2.0,reversable,Yes
76,77,60,1,asymptomatic,125,258,0,2,141,1,2.8,2,1.0,reversable,Yes
272,273,46,1,asymptomatic,140,311,0,0,120,1,1.8,2,2.0,reversable,Yes
238,239,49,0,nontypical,134,271,0,0,162,0,0.0,2,0.0,normal,No